class Solution:
        def resultArray(self, nums, k, queries):
                n = len(nums)

                        # tree[node] = (product % k, count of prefix remainders)
                                tree = [(1, [0] * k) for _ in range(4 * n)]

                                        def merge(left, right):
                                                    left_prod, left_cnt = left
                                                                right_prod, right_cnt = right

                                                                            # Product of the whole combined segment
                                                                                        prod = (left_prod * right_prod) % k

                                                                                                    # Start with prefixes that are completely inside the left segment
                                                                                                                cnt = left_cnt[:]

                                                                                                                            # Add prefixes that cross from left into right
                                                                                                                                        for r in range(k):
                                                                                                                                                        new_remainder = (left_prod * r) % k
                                                                                                                                                                        cnt[new_remainder] += right_cnt[r]

                                                                                                                                                                                    return prod, cnt

                                                                                                                                                                                            def build(node, l, r):
                                                                                                                                                                                                        if l == r:
                                                                                                                                                                                                                        value = nums[l] % k

                                                                                                                                                                                                                                        # The only prefix is [nums[l]]
                                                                                                                                                                                                                                                        cnt = [0] * k
                                                                                                                                                                                                                                                                        cnt[value] = 1

                                                                                                                                                                                                                                                                                        tree[node] = (value, cnt)
                                                                                                                                                                                                                                                                                                        return

                                                                                                                                                                                                                                                                                                                    mid = (l + r) // 2

                                                                                                                                                                                                                                                                                                                                build(node * 2, l, mid)
                                                                                                                                                                                                                                                                                                                                            build(node * 2 + 1, mid + 1, r)

                                                                                                                                                                                                                                                                                                                                                        tree[node] = merge(
                                                                                                                                                                                                                                                                                                                                                                        tree[node * 2],
                                                                                                                                                                                                                                                                                                                                                                                        tree[node * 2 + 1]
                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                            def update(node, l, r, index, value):
                                                                                                                                                                                                                                                                                                                                                                                                                        if l == r:
                                                                                                                                                                                                                                                                                                                                                                                                                                        value %= k

                                                                                                                                                                                                                                                                                                                                                                                                                                                        cnt = [0] * k
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cnt[value] = 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tree[node] = (value, cnt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mid = (l + r) // 2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if index <= mid:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                update(node * 2, l, mid, index, value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            update(node * 2 + 1, mid + 1, r, index, value)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tree[node] = merge(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tree[node * 2],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tree[node * 2 + 1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def query(node, l, r, ql, qr):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Current segment is completely inside the query range
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ql <= l and r <= qr:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return tree[node]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mid = (l + r) // 2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Query only the left child
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if qr <= mid:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return query(node * 2, l, mid, ql, qr)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Query only the right child
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if ql > mid:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return query(node * 2 + 1, mid + 1, r, ql, qr)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Query both sides.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # IMPORTANT: merge left first, then right.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    left = query(node * 2, l, mid, ql, qr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                right = query(node * 2 + 1, mid + 1, r, ql, qr)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return merge(left, right)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    build(1, 0, n - 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            answer = []

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for index, value, start, x in queries:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Update persists for all future queries
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            update(1, 0, n - 1, index, value)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # After removing nums[0:start],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # every possible remaining array is a prefix
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # of nums[start:n].
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result = query(1, 0, n - 1, start, n - 1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        answer.append(result[1][x])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return answer